### ISSUE TITLE
Getting error at installing time.

### ISSUE THREAD

**Issue by pavan7parekh** [AssemblyPayments/spi-client-windows#1]
A project structure is containing a PCL. Within this PCL, I tried to install SPIClient using NuGet, but that's simply not possible.

Console output:
> Could not install package 'SPIClient 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ellulpatrick** [comment]
Hi Pavan. Are you using this for Xamarin? It is a valid issue, we will work on adding a .NETPortable target to the package that would work for you in this case.

**Comment by pavan7parekh** [comment]
Hi @ellulpatrick,

Yes, I am using this for Xamarin.Forms.

**Comment by Raymond-Ko82** [comment]
Hi @pavan7parekh 

Sorry for the delayed response. We will be looking at a release this week to support PCL.

**Comment by pavan7parekh** [comment]
Ok! Thanks,
I will start implementation once you done.

**Comment by pavan7parekh** [comment]
@RaymondK-AP 

You can contact me on pavan7parekh@yahoo.com

Thank You,
Pavan
